.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/EmisoraBLE.h" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/EmisoraBLE.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ServicioEnEmisora\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmisoraBLE\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
