.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/LED.h" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/LED.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLED\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBesperar\fP (long tiempo)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void esperar (long tiempo)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
