.TH "Medidor" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Medidor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Medidor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMedidor\fP ()"
.br
.ti -1c
.RI "void \fBiniciarMedidor\fP ()"
.br
.ti -1c
.RI "int \fBmedirCO2\fP ()"
.br
.ti -1c
.RI "int \fBmedirTemperatura\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Medidor::Medidor ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Medidor::iniciarMedidor ()\fC [inline]\fP"

.SS "int Medidor::medirCO2 ()\fC [inline]\fP"

.SS "int Medidor::medirTemperatura ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
