.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/Medidor.h" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/Medidor.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMedidor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBmedida_temp\fP (double Vtemp)"
.br
.ti -1c
.RI "void \fBSerial1InParser\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBsensorData\fP [11]"
.br
.ti -1c
.RI "int \fBPgas\fP = 5"
.br
.ti -1c
.RI "int \fBPref\fP = 28"
.br
.ti -1c
.RI "int \fBPtemp\fP = 29"
.br
.ti -1c
.RI "int \fBVgas_value\fP = 0"
.br
.ti -1c
.RI "int \fBVref_value\fP = 0"
.br
.ti -1c
.RI "int \fBVtmp_value\fP = 0"
.br
.ti -1c
.RI "float \fBM\fP = 499 * pow(10, \-6)"
.br
.ti -1c
.RI "float \fBsensitivityCode\fP = \-41\&.26"
.br
.ti -1c
.RI "float \fBresultado\fP = \fBsensitivityCode\fP * \fBM\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double medida_temp (double Vtemp)"

.SS "void Serial1InParser ()"

.SH "Variable Documentation"
.PP 
.SS "float M = 499 * pow(10, \-6)"

.SS "int Pgas = 5"

.SS "int Pref = 28"

.SS "int Ptemp = 29"

.SS "float resultado = \fBsensitivityCode\fP * \fBM\fP"

.SS "float sensitivityCode = \-41\&.26"

.SS "int sensorData[11]"

.SS "int Vgas_value = 0"

.SS "int Vref_value = 0"

.SS "int Vtmp_value = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
