.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/ServicioEnEmisora.h" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/arduino/HolaMundoIBeacon/HolaMundoIBeacon/ServicioEnEmisora.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBServicioEnEmisora\fP"
.br
.ti -1c
.RI "class \fBServicioEnEmisora::Caracteristica\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T * \fBalReves\fP (T *p, int n)"
.br
.ti -1c
.RI "uint8_t * \fBstringAUint8AlReves\fP (const char *pString, uint8_t *pUint, int tamMax)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > T * alReves (T * p, int n)"

.SS "uint8_t * stringAUint8AlReves (const char * pString, uint8_t * pUint, int tamMax)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
