.TH "com.example.myapplication.PeticionarioREST.RespuestaREST" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.myapplication.PeticionarioREST.RespuestaREST
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcallback\fP (int codigo, String cuerpo)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void com\&.example\&.myapplication\&.PeticionarioREST\&.RespuestaREST\&.callback (int codigo, String cuerpo)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
