.TH "com.example.myapplication" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.myapplication
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogica\fP"
.br
.ti -1c
.RI "class \fBMainActivity\fP"
.br
.ti -1c
.RI "class \fBMedidas\fP"
.br
.ti -1c
.RI "class \fBPeticionarioREST\fP"
.br
.ti -1c
.RI "class \fBTramaIBeacon\fP"
.br
.ti -1c
.RI "class \fBUtilidades\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
