.TH "com.example.myapplication.PeticionarioREST" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.myapplication.PeticionarioREST
.SH SYNOPSIS
.br
.PP
.PP
Inherits AsyncTask< Void, Void, Boolean >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBRespuestaREST\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhacerPeticionREST\fP (String metodo, String urlDestino, String cuerpo, \fBRespuestaREST\fP laRespuesta)"
.br
.ti -1c
.RI "\fBPeticionarioREST\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Boolean \fBdoInBackground\fP (Void\&.\&.\&. params)"
.br
.ti -1c
.RI "void \fBonPostExecute\fP (Boolean comoFue)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.example\&.myapplication\&.PeticionarioREST\&.PeticionarioREST ()"

.SH "Member Function Documentation"
.PP 
.SS "Boolean com\&.example\&.myapplication\&.PeticionarioREST\&.doInBackground (Void\&.\&.\&. params)\fC [protected]\fP"

.SS "void com\&.example\&.myapplication\&.PeticionarioREST\&.hacerPeticionREST (String metodo, String urlDestino, String cuerpo, \fBRespuestaREST\fP laRespuesta)"

.SS "void com\&.example\&.myapplication\&.PeticionarioREST\&.onPostExecute (Boolean comoFue)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
