.TH "com.example.myapplication.Utilidades" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.myapplication.Utilidades
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static byte[] \fBstringToBytes\fP (String texto)"
.br
.ti -1c
.RI "static UUID \fBstringToUUID\fP (String uuid)"
.br
.ti -1c
.RI "static String \fBuuidToString\fP (UUID uuid)"
.br
.ti -1c
.RI "static String \fBuuidToHexString\fP (UUID uuid)"
.br
.ti -1c
.RI "static String \fBbytesToString\fP (byte[] bytes)"
.br
.ti -1c
.RI "static byte[] \fBdosLongToBytes\fP (long masSignificativos, long menosSignificativos)"
.br
.ti -1c
.RI "static int \fBbytesToInt\fP (byte[] bytes)"
.br
.ti -1c
.RI "static long \fBbytesToLong\fP (byte[] bytes)"
.br
.ti -1c
.RI "static int \fBbytesToIntOK\fP (byte[] bytes)"
.br
.ti -1c
.RI "static String \fBbytesToHexString\fP (byte[] bytes)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static String com\&.example\&.myapplication\&.Utilidades\&.bytesToHexString (byte[] bytes)\fC [static]\fP"

.SS "static int com\&.example\&.myapplication\&.Utilidades\&.bytesToInt (byte[] bytes)\fC [static]\fP"

.SS "static int com\&.example\&.myapplication\&.Utilidades\&.bytesToIntOK (byte[] bytes)\fC [static]\fP"

.SS "static long com\&.example\&.myapplication\&.Utilidades\&.bytesToLong (byte[] bytes)\fC [static]\fP"

.SS "static String com\&.example\&.myapplication\&.Utilidades\&.bytesToString (byte[] bytes)\fC [static]\fP"

.SS "static byte[] com\&.example\&.myapplication\&.Utilidades\&.dosLongToBytes (long masSignificativos, long menosSignificativos)\fC [static]\fP"

.SS "static byte[] com\&.example\&.myapplication\&.Utilidades\&.stringToBytes (String texto)\fC [static]\fP"

.SS "static UUID com\&.example\&.myapplication\&.Utilidades\&.stringToUUID (String uuid)\fC [static]\fP"

.SS "static String com\&.example\&.myapplication\&.Utilidades\&.uuidToHexString (UUID uuid)\fC [static]\fP"

.SS "static String com\&.example\&.myapplication\&.Utilidades\&.uuidToString (UUID uuid)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
