.TH "com.example.myapplication.TramaIBeacon" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.myapplication.TramaIBeacon
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "byte[] \fBgetPrefijo\fP ()"
.br
.ti -1c
.RI "byte[] \fBgetUUID\fP ()"
.br
.ti -1c
.RI "byte[] \fBgetMajor\fP ()"
.br
.ti -1c
.RI "byte[] \fBgetMinor\fP ()"
.br
.ti -1c
.RI "byte \fBgetTxPower\fP ()"
.br
.ti -1c
.RI "byte[] \fBgetLosBytes\fP ()"
.br
.ti -1c
.RI "byte[] \fBgetAdvFlags\fP ()"
.br
.ti -1c
.RI "byte[] \fBgetAdvHeader\fP ()"
.br
.ti -1c
.RI "byte[] \fBgetCompanyID\fP ()"
.br
.ti -1c
.RI "byte \fBgetiBeaconType\fP ()"
.br
.ti -1c
.RI "byte \fBgetiBeaconLength\fP ()"
.br
.ti -1c
.RI "\fBTramaIBeacon\fP (byte[] bytes)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.example\&.myapplication\&.TramaIBeacon\&.TramaIBeacon (byte[] bytes)"

.SH "Member Function Documentation"
.PP 
.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getAdvFlags ()"

.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getAdvHeader ()"

.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getCompanyID ()"

.SS "byte com\&.example\&.myapplication\&.TramaIBeacon\&.getiBeaconLength ()"

.SS "byte com\&.example\&.myapplication\&.TramaIBeacon\&.getiBeaconType ()"

.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getLosBytes ()"

.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getMajor ()"

.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getMinor ()"

.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getPrefijo ()"

.SS "byte com\&.example\&.myapplication\&.TramaIBeacon\&.getTxPower ()"

.SS "byte[] com\&.example\&.myapplication\&.TramaIBeacon\&.getUUID ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
