.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/htdocs/Proyecto_Biometria/src/api/v1.0/bbdd.php" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/htdocs/Proyecto_Biometria/src/api/v1.0/bbdd.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbbddInsert\fP ($Medicion, $TipoSensor, $Latitud, $Longitud)"
.br
.ti -1c
.RI "\fBbuscarBBDD\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bbddInsert ( $Medicion,  $TipoSensor,  $Latitud,  $Longitud)"
Noureddine Tallal Sprint 0 :Proyecto Medio ambiente insertar datos en la base de datos 
.br
 devolver los datos de la base de datos
.PP
---------------------Me faltan los tests-------------------------------- 
.SS "buscarBBDD ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
