.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/htdocs/Proyecto_Biometria/src/api/v1.0 Directory Reference" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/htdocs/Proyecto_Biometria/src/api/v1.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbbdd\&.php\fP"
.br
.ti -1c
.RI "file \fBconexion\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBlogica\&.php\fP"
.br
.in -1c
