.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/htdocs/Proyecto_Biometria/src/api/v1.0/index.php" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/htdocs/Proyecto_Biometria/src/api/v1.0/index.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$_METODO\fP = $_SERVER['REQUEST_METHOD']"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$_METODO = $_SERVER['REQUEST_METHOD']"
Noureddine Tallal
.PP
Proyecto Medio ambiente ------------Handling the request---------------------- 
.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
