.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/MyApplication/app/src/main/java/com/example/myapplication Directory Reference" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/MyApplication/app/src/main/java/com/example/myapplication Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLogica\&.java\fP"
.br
.ti -1c
.RI "file \fBMainActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBMedidas\&.java\fP"
.br
.ti -1c
.RI "file \fBPeticionarioREST\&.java\fP"
.br
.ti -1c
.RI "file \fBTramaIBeacon\&.java\fP"
.br
.ti -1c
.RI "file \fBUtilidades\&.java\fP"
.br
.in -1c
