.TH "C:/Users/stips/Desktop/Sprint0_Tallal - copia/MyApplication/app/src Directory Reference" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/stips/Desktop/Sprint0_Tallal - copia/MyApplication/app/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmain\fP"
.br
.in -1c
