.TH "com.example.myapplication.MainActivity" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.myapplication.MainActivity
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppCompatActivity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbotonBuscarDispositivosBTLEPulsado\fP (View v)"
.br
.ti -1c
.RI "void \fBbotonBuscarNuestroDispositivoBTLEPulsado\fP (View v)"
.br
.ti -1c
.RI "void \fBbotonDetenerBusquedaDispositivosBTLEPulsado\fP (View v)"
.br
.ti -1c
.RI "void \fBonRequestPermissionsResult\fP (int requestCode, String[] permissions, int[] grantResults)"
.br
.ti -1c
.RI "void \fBboton_enviar_pulsado_client\fP (View quien)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Button \fBmandarPost\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void com\&.example\&.myapplication\&.MainActivity\&.boton_enviar_pulsado_client (View quien)"

.SS "void com\&.example\&.myapplication\&.MainActivity\&.botonBuscarDispositivosBTLEPulsado (View v)"

.SS "void com\&.example\&.myapplication\&.MainActivity\&.botonBuscarNuestroDispositivoBTLEPulsado (View v)"

.SS "void com\&.example\&.myapplication\&.MainActivity\&.botonDetenerBusquedaDispositivosBTLEPulsado (View v)"

.SS "void com\&.example\&.myapplication\&.MainActivity\&.onCreate (Bundle savedInstanceState)\fC [protected]\fP"

.SS "void com\&.example\&.myapplication\&.MainActivity\&.onRequestPermissionsResult (int requestCode, String[] permissions, int[] grantResults)"

.SH "Member Data Documentation"
.PP 
.SS "Button com\&.example\&.myapplication\&.MainActivity\&.mandarPost"


.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
