.TH "com.example.myapplication.Medidas" 3 "Medio Ambiente" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.example.myapplication.Medidas
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetMedicion\fP ()"
.br
.ti -1c
.RI "void \fBsetMedicion\fP (int medicion)"
.br
.ti -1c
.RI "\fBMedidas\fP (int medicion, int tipoSensor, double latitud, double longitud)"
.br
.ti -1c
.RI "int \fBgetTipoSensor\fP ()"
.br
.ti -1c
.RI "void \fBsetTipoSensor\fP (int tipoSensor)"
.br
.ti -1c
.RI "double \fBgetLatitud\fP ()"
.br
.ti -1c
.RI "void \fBsetLatitud\fP (double latitud)"
.br
.ti -1c
.RI "double \fBgetLongitud\fP ()"
.br
.ti -1c
.RI "void \fBsetLongitud\fP (double longitud)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.example\&.myapplication\&.Medidas\&.Medidas (int medicion, int tipoSensor, double latitud, double longitud)"

.SH "Member Function Documentation"
.PP 
.SS "double com\&.example\&.myapplication\&.Medidas\&.getLatitud ()"

.SS "double com\&.example\&.myapplication\&.Medidas\&.getLongitud ()"

.SS "int com\&.example\&.myapplication\&.Medidas\&.getMedicion ()"

.SS "int com\&.example\&.myapplication\&.Medidas\&.getTipoSensor ()"

.SS "void com\&.example\&.myapplication\&.Medidas\&.setLatitud (double latitud)"

.SS "void com\&.example\&.myapplication\&.Medidas\&.setLongitud (double longitud)"

.SS "void com\&.example\&.myapplication\&.Medidas\&.setMedicion (int medicion)"

.SS "void com\&.example\&.myapplication\&.Medidas\&.setTipoSensor (int tipoSensor)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Medio Ambiente from the source code\&.
